### ISSUE TITLE
Bus error on Raspberry Pi 3B during unit test run

### ISSUE THREAD

**Issue by 0x72D0** [ihhub/penguinV#137] opened 2018-10-12 21:47 UTC
device: raspberry 3B
cpu: cortex-a53
linux kernel: 4.9.35-v7+

I get the following error when running the unit test on a raspberry pi model 3B:

![2018-10-12-213909_1824x984_scrot](https://user-images.githubusercontent.com/16087328/46895534-5901a200-ce68-11e8-8206-bc5327d3ebf7.png)

**Comment by ihhub** [comment] 2018-10-13 01:50
Function pool uses thread pool which contains multiple threads. The problem could lie in thread handling within the system. I'll take a look what does this error mean...

**Comment by ihhub** [comment] 2018-10-13 01:54
Looks like it an attempt to invalid memory. It could be due NEON instructions usage accessing memory without a proper alignment. Please try to disable neon instructions for now (in `cpu_id_unix.h just return false).

**Comment by 0x72D0** [comment] 2018-10-13 16:03
ok I made the cpu_id_unix.h file always return false for the isNeonSupported function and it gave me the same result. But it look like it always happen to the function_pool::ConvertToGrayScale. it also happen with the unit_tests program:

![2018-10-13-155611_1824x984_scrot](https://user-images.githubusercontent.com/16087328/46907409-78004280-cf01-11e8-84fd-fe30bee31b71.png)

I will try to debug it and send a stacktrace or something

**Comment by 0x72D0** [comment] 2018-10-13 16:28
ok here is what I obtain with gdb (with the gef plugin):

![2018-10-13-162132_1824x984_scrot](https://user-images.githubusercontent.com/16087328/46907636-0aeeac00-cf05-11e8-9cac-093a82502939.png)

**Comment by 0x72D0** [comment] 2018-10-13 16:29
seems to be a thread problem like you said earlier.

**Comment by ihhub** [comment] 2018-10-14 01:30
`function_pool::ConvertToGrayScale` always comes first in your case due to non randomise address assignment for functions. I'm not sure how thread creation could fail. Could you please comment all function pool functions for unit tests? If unit tests would succeed then I create another issue for this. Do not forget to return back `cpuid_unix.h` to original state after commenting function pool.

**Comment by ihhub** [comment] 2018-10-14 01:35
Another try: could you please compile it with debug flag (add inside makefile option -g) and then run with `lldb` (or `gdb`)? After the crash check the call stack (`bt all`)? [Here](https://lldb.llvm.org/lldb-gdb.html) you could find all useful commands for `gdb` and `lldb`.

**Comment by 0x72D0** [comment] 2018-10-14 03:04
I already compile it with the debug flag in the gdb scrrenshot and when I type "bt all" hdb respond with : No symbol "all" in current context. You can have a little backtrace in the gdb screenshot I already send.

**Comment by ihhub** [comment] 2018-10-16 00:35
I'm trying to find another Raspberry Pi for testing to see what's going on.

**Comment by ihhub** [comment] 2018-10-16 14:17
I ran unit tests on Raspberry Pi 3B with `-mfpu=neon-vfpv4` instead of `-march=native` flag. All tests are passed. Try this way please. If it still does not work it might be some issues with your drivers/libraries.

**Comment by 0x72D0** [comment] 2018-10-27 06:05
ok, -mcpu=cortex-a53 was the culprit behind the bus error, with only -mfpu=neon-vfpv4, it works like a charm!

**Comment by ihhub** [comment] 2018-10-27 06:07
Great. At least we know the fix so we could somehow modify or add a description to end user.

**Comment by ihhub** [comment] 2018-11-17 15:18
@0x72D0 I suppose that the issue is still present. Is the OS which is install on your Raspberry PI is **Raspbian**?

**Comment by 0x72D0** [comment] 2018-11-17 15:45
yes it is raspbian, but I have no issue if I remove the `mcpu=cortex-a53` so I'm closing this issue.

**Comment by ihhub** [comment] 2018-11-17 15:50
No need to close it. We need to make a proper solution to fix the same problem for other people who would try to compile the library on Raspberry Pi.

@yannlabou I'm thinking to add a code in cmake file to detect current OS. If this OS is Raspberry Pi we would set `-mfpu=neon-vfpv4` flag for compilation. What do you think?

**Comment by 0x72D0** [comment] 2018-11-17 15:55
yeah it should fix the problem :)

**Comment by yannlabou** [comment] 2018-11-17 16:08
@ihhub It should be doable to detect if the current Linux flavor is a raspbian with CMake. Please file an issue and assign it to me. As I don’t have the hardware, someone else will have to test it.

**Comment by 0x72D0** [comment] 2018-11-17 16:09
@yannlabou when you think you have something functional contact me, I will test it

**Comment by yannlabou** [comment] 2018-11-17 16:10
> @yannlabou when you think you have something functional contact me, I will test it

Cool. Will do.

**Comment by ihhub** [comment] 2019-05-15 02:46
Hey @yannlabou do you have a time to try to fix this issue with CMake as mentioned above? I can create a separate issue for this if needed.

**Comment by yannlabou** [comment] 2019-05-15 08:09
Yeah. Let's create a new issue for that and I'll take care.

**Comment by ihhub** [comment] 2019-05-21 13:32
@0x72D0 can we confirm that this issue is fixed now?

**Comment by 0x72D0** [comment] 2019-05-21 18:29
yes

**Closed** 2019-05-21 23:13 UTC
Labels: Hacktoberfest, bug
